const cars = [
  { name: "Model S", brand: "Tesla", price: 80000 },
  { name: "Model 3", brand: "Tesla", price: 35000 },
  { name: "Model X", brand: "Tesla", price: 90000 },
  { name: "Model Y", brand: "Tesla", price: 40000 },
  { name: "Corolla", brand: "Toyota", price: 20000 },
  { name: "Camry", brand: "Toyota", price: 25000 },
  { name: "Prius", brand: "Toyota", price: 30000 },
  { name: "Accord", brand: "Honda", price: 28000 },
  { name: "Civic", brand: "Honda", price: 22000 },
  { name: "CR-V", brand: "Honda", price: 32000 },
  { name: "F-150", brand: "Ford", price: 40000 },
  { name: "Mustang", brand: "Ford", price: 35000 },
  { name: "Explorer", brand: "Ford", price: 45000 },
  { name: "Camaro", brand: "Chevrolet", price: 38000 },
  { name: "Impala", brand: "Chevrolet", price: 32000 },
  { name: "Equinox", brand: "Chevrolet", price: 28000 },
  { name: "Challenger", brand: "Dodge", price: 42000 },
  { name: "Charger", brand: "Dodge", price: 38000 },
  { name: "Durango", brand: "Dodge", price: 45000 },
  { name: "Wrangler", brand: "Jeep", price: 35000 },
];

const students = [
  { name: "Alice", year: "Freshman", grades: [80, 90, 85] },
  { name: "Bob", year: "Sophomore", grades: [70, 75, 80] },
  { name: "Charlie", year: "Junior", grades: [85, 90, 95] },
  { name: "David", year: "Senior", grades: [60, 65, 70] },
  { name: "Eve", year: "Freshman", grades: [90, 95, 100] },
  { name: "Frank", year: "Sophomore", grades: [75, 80, 85] },
  { name: "Grace", year: "Junior", grades: [85, 90, 95] },
  { name: "Henry", year: "Senior", grades: [70, 75, 80] },
  { name: "Isaac", year: "Freshman", grades: [80, 85, 90] },
  { name: "Jane", year: "Sophomore", grades: [75, 80, 85] },
  { name: "Kevin", year: "Junior", grades: [90, 95, 100] },
  { name: "Linda", year: "Senior", grades: [70, 75, 80] },
  { name: "Mike", year: "Freshman", grades: [85, 90, 95] },
  { name: "Nancy", year: "Sophomore", grades: [80, 85, 90] },
  { name: "Oliver", year: "Junior", grades: [75, 80, 85] },
  { name: "Pamela", year: "Senior", grades: [90, 95, 100] },
  { name: "Quincy", year: "Freshman", grades: [70, 75, 80] },
  { name: "Rachel", year: "Sophomore", grades: [85, 90, 95] },
  { name: "Steve", year: "Junior", grades: [80, 85, 90] },
  { name: "Tina", year: "Senior", grades: [75, 80, 85] },
];

const employees = [
  { name: "Alice", title: "Manager", hourly_rate: 50.0, worked_hours: 40 },
  { name: "Bob", title: "Developer", hourly_rate: 30.0, worked_hours: 50 },
  { name: "Charlie", title: "Designer", hourly_rate: 25.0, worked_hours: 35 },
  { name: "David", title: "Developer", hourly_rate: 30.0, worked_hours: 45 },
  { name: "Eve", title: "Manager", hourly_rate: 50.0, worked_hours: 40 },
  { name: "Frank", title: "Developer", hourly_rate: 30.0, worked_hours: 55 },
  { name: "Grace", title: "Designer", hourly_rate: 25.0, worked_hours: 40 },
  { name: "Henry", title: "Developer", hourly_rate: 30.0, worked_hours: 50 },
  { name: "Isaac", title: "Manager", hourly_rate: 50.0, worked_hours: 40 },
  { name: "Jane", title: "Developer", hourly_rate: 30.0, worked_hours: 45 },
  { name: "Kevin", title: "Designer", hourly_rate: 25.0, worked_hours: 35 },
  { name: "Linda", title: "Developer", hourly_rate: 30.0, worked_hours: 50 },
  { name: "Mike", title: "Manager", hourly_rate: 50.0, worked_hours: 40 },
  { name: "Nancy", title: "Developer", hourly_rate: 30.0, worked_hours: 45 },
  { name: "Oliver", title: "Designer", hourly_rate: 25.0, worked_hours: 40 },
  { name: "Pamela", title: "Developer", hourly_rate: 30.0, worked_hours: 50 },
  { name: "Quincy", title: "Manager", hourly_rate: 50.0, worked_hours: 40 },
  { name: "Rachel", title: "Developer", hourly_rate: 30.0, worked_hours: 45 },
  { name: "Steve", title: "Designer", hourly_rate: 25.0, worked_hours: 35 },
  { name: "Tina", title: "Developer", hourly_rate: 30.0, worked_hours: 50 },
];
